### ISSUE TITLE
`ots` field no longer defined in NIP-03

### ISSUE THREAD

**Issue by theborakompanioni** [penpenpng/nostr-typedef#12]
Came across this line:

https://github.com/penpenpng/nostr-typedef/blob/af6eb51c3b08fe99578a32847f82eeb3f230305c/index.d.ts#L14-L15

`ots` has been removed in [09ffb95](https://github.com/nostr-protocol/nips/commit/09ffb951c69343312486aaff2726dca04bc42f6e). Should it be kept? Marked as deprecated?
Personally, I think it would be nice to have it removed in v1.0.0 :-)
What do you think?

**Comment by penpenpng** [comment]
I'll mark it as deprecated. There are no plans to release v1 at this time, but if and when I do, all deprecated fields will be removed.

**Comment by penpenpng** [comment]
v0.11.0 has been released. As noted above, there is no plan for v1 at this time, so this is closed for now. Thanks!
